--VRAAG 1
CREATE TABLE VRAAG2_1 AS
SELECT CHAR_DATE, AC_NUMBER, CHAR_DESTINATION,
CHAR_DISTANCE, CHAR_HOURS_FLOWN
FROM CHARTER
WHERE AC_NUMBER = '2778V';

--VRAAG 2
CREATE TABLE VRAAG2_2 AS 
SELECT CHAR_DATE, AC_NUMBER, CHAR_HOURS_FLOWN, 
CHAR_FUEL_GALLONS, CHAR_FUEL_GALLONS/CHAR_HOURS_FLOWN AS GALLONS_PER_HOUR
FROM CHARTER
WHERE CHAR_HOURS_FLOWN > 0;

--VRAAG 3
CREATE TABLE VRAAG2_3 AS 
SELECT CUS_LNAME,CUS_FNAME,CUS_INITIAL,CUS_BALANCE
FROM CUSTOMER
WHERE CUS_BALANCE > 0;

--VRAAG 4
CREATE TABLE VRAAG2_4 AS
SELECT AVG(CUS_BALANCE) AS GEMIDDELDE_BALANS,
MIN(CUS_BALANCE) AS MINIMUM_BALANS,
MAX(CUS_BALANCE) AS MAKSIMUM_BALANS, 
SUM(CUS_BALANCE) AS TOTALE_BALANS
FROM CUSTOMER;

--VRAAG 5
CREATE TABLE VRAAG2_5 AS
SELECT EMP_NUM, EMP_LNAME, EMP_FNAME,EMP_HIRE_DATE,EMP_DOB, 
CURRENT_DATE-EMP_DOB AS OUDERDOM
FROM EMPLOYEE;

--VRAAG 6
INSERT INTO EMPLOYEE
VALUES(111,'Mr.','Pieterse','Riko','B','1985-05-06','2024-08-19');

INSERT INTO PILOT
VALUES (111,'COM','SEL/MEL/Instr/CFI','2','2013-01-15','2023-11-23');

--VRAAG 7
CREATE TABLE VRAAG2_7 AS
SELECT * FROM EMPLOYEE
WHERE EMP_LNAME != 'VanDam';